#!/usr/bin/env bash
# Generate design tokens in multiple formats from a JSON token source
# Usage: generate-tokens.sh <tokens.json> <output-dir> [--formats json,css,scss,tailwind]
#
# Input: A JSON file with the brandy token structure:
# {
#   "color": { "primary": "#...", "secondary": "#...", ... },
#   "spacing": { "xs": "4px", "sm": "8px", ... },
#   "typography": { "fontFamily": { "primary": "...", "secondary": "..." }, ... },
#   "borderRadius": { "sm": "4px", ... }
# }
#
# Output:
#   output-dir/
#   ├── tokens.json          (canonical JSON)
#   ├── tokens.css           (CSS custom properties)
#   ├── _tokens.scss         (SCSS variables)
#   └── tailwind.tokens.js   (Tailwind theme extension)

set -euo pipefail

INPUT_JSON="${1:-}"
OUTPUT_DIR="${2:-}"
FORMATS="${3:---formats json,css,scss,tailwind}"

if [[ -z "$INPUT_JSON" || -z "$OUTPUT_DIR" ]]; then
  echo '{"error": "Usage: generate-tokens.sh <tokens.json> <output-dir> [--formats json,css,scss,tailwind]"}'
  exit 1
fi

if [[ ! -f "$INPUT_JSON" ]]; then
  echo "{\"error\": \"Input file not found: $INPUT_JSON\"}"
  exit 1
fi

if ! command -v node &>/dev/null; then
  echo '{"error": "Node.js is required for token generation"}'
  exit 1
fi

FORMATS_STR="${FORMATS#--formats }"
mkdir -p "$OUTPUT_DIR"

# Use Node.js for reliable JSON processing and format conversion
BRANDY_INPUT="$INPUT_JSON" BRANDY_OUT="$OUTPUT_DIR" BRANDY_FORMATS="$FORMATS_STR" node -e "
const fs = require('fs');
const path = require('path');

const tokens = JSON.parse(fs.readFileSync(process.env.BRANDY_INPUT, 'utf-8'));
const outDir = process.env.BRANDY_OUT;
const formats = process.env.BRANDY_FORMATS.split(',');
const files = [];

// Flatten nested tokens into key-value pairs with prefix
function flatten(obj, prefix = '') {
  const result = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? prefix + '-' + key : key;
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      result.push(...flatten(value, fullKey));
    } else {
      result.push({ key: fullKey, value: String(value) });
    }
  }
  return result;
}

const flat = flatten(tokens);

// JSON (canonical copy)
if (formats.includes('json')) {
  const outPath = path.join(outDir, 'tokens.json');
  fs.writeFileSync(outPath, JSON.stringify(tokens, null, 2) + '\n');
  files.push('tokens.json');
}

// CSS custom properties
if (formats.includes('css')) {
  let css = '/* Generated by Brandy — do not edit manually */\n:root {\n';
  for (const { key, value } of flat) {
    css += '  --' + key + ': ' + value + ';\n';
  }
  css += '}\n';
  const outPath = path.join(outDir, 'tokens.css');
  fs.writeFileSync(outPath, css);
  files.push('tokens.css');
}

// SCSS variables
if (formats.includes('scss')) {
  let scss = '// Generated by Brandy — do not edit manually\n';
  for (const { key, value } of flat) {
    scss += '\$' + key + ': ' + value + ';\n';
  }
  const outPath = path.join(outDir, '_tokens.scss');
  fs.writeFileSync(outPath, scss);
  files.push('_tokens.scss');
}

// Tailwind theme extension
if (formats.includes('tailwind')) {
  // Build a nested Tailwind-friendly config
  function toTailwind(obj) {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
        result[key] = toTailwind(value);
      } else {
        result[key] = String(value);
      }
    }
    return result;
  }

  const tw = toTailwind(tokens);
  let js = '// Generated by Brandy — do not edit manually\n';
  js += '/** @type {import(\"tailwindcss\").Config[\"theme\"]} */\n';
  js += 'module.exports = ' + JSON.stringify(tw, null, 2) + ';\n';
  const outPath = path.join(outDir, 'tailwind.tokens.js');
  fs.writeFileSync(outPath, js);
  files.push('tailwind.tokens.js');
}

console.log(JSON.stringify({ status: 'complete', output_dir: outDir, files }));
"
